services:
  - type: web
    name: shl-recommender
    runtime: docker
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
